.\" Manpage for reveal
.\" MIT License
.TH REVEAL 1 "08 May 2023" "inopinatus" "Reveal User Manual"
.SH NAME
reveal \- Reveal selected files or directories in Finder
.SH SYNOPSIS
.B reveal
.RI [ -0 ]
.RI [ -- ]
.RI [ files... ]
.SH DESCRIPTION
.PP
.B reveal
is a utility for revealing selected files in MacOS Finder.
.PP
The options are as follows:
.TP
.BI -0
Expect NUL ('\\0')-terminated filename strings on stdin.
.TP
.BI --
End of options processing; all subsequent arguments are files.
.PP
Either absolute and relative paths may be supplied, and may be mixed
in the same invocation.  Relative paths will be resolved from the
current working directory.
.PP
Paths may be passed as arguments, or from standard input, but not
both.  If supplied via arguments whilst stdin has data available,
then stdin will be ignored and the arguments will be used, and a
warning will be issued.  This warning is suppressed by the
.BI --
option.
.PP
Always supply the
.BI --
option when passing filename(s) via arguments from within another
script/application.  Not only does it silence the warning, this
prevents misbehaviour when a relative path begins with a hyphen.
.PP
You may expect the Finder to open as many folder windows as sufficient
and necessary to reveal all files specified.  Files that do not
exist are silently ignored.
.SH EXAMPLES
Open Finder and select files passed as arguments:
.PP
.nf
\fBreveal file1.txt file2.txt\fR
.fi
.PP
Find and reveal files with a PDF extension in your Documents folder and subfolders:
.PP
.nf
\fBfind ~/Documents -iname '*.pdf' -print0 | reveal -0\fR
.fi
.PP
Reveal a file supplied from user input:
.PP
.nf
\fBread FILENAME\fR
\fBreveal -- "$FILENAME"\fR
.fi
.SH CONTRIBUTING
.PP
Visit the Github project: https://github.com/inopinatus/reveal
.SH SEE ALSO
.BR find (1),
.BR open (1)
